# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('date', models.TextField()),
                ('valid', models.BooleanField()),
                ('taxId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.TextField(max_length=10, unique=True)),
                ('date', models.TextField()),
                ('money', models.IntegerField()),
                ('taxid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.TextField()),
                ('date', models.TextField()),
                ('direction', models.IntegerField()),
                ('distance', models.IntegerField(default=100)),
                ('fail_cnt', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('queued', models.BooleanField(default=False)),
                ('todo', models.TextField(null=True)),
                ('succ', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('rps', models.FloatField(default=0.0)),
                ('success', models.IntegerField()),
                ('error', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskServer.Task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('receipt', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together=set([('receipt', 'date')]),
        ),
    ]
